openapi: "3.0.0"
info:
  version: 1.0.0
  title: Example
  license:
    name: MIT
servers:
  - url: /
paths:
  /pet:
    get:
      tags:
        - pets
      responses:
        '200':
          description: 'A description'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
        kindOf:
          type: object
          oneOf:
            - $ref: '#/components/schemas/Fish'
            - $ref: '#/components/schemas/Mammal'
    Fish:
      type: object
      properties:
        location:
          type: string
    Mammal:
      type: object
      properties:
        location:
          type: string

